### ISSUE TITLE
SRS-012: The CSC OMOP service shall record project statuses

### ISSUE THREAD

**Issue by dangerdika** [GSTT-CSC/OMOP#15]
## Description
The CSC OMOP service should be able to update the statuses e.g., approved, rejected, or backlog, of submitted project requests e.g., stored in the `csc.admin.projects` table.

These updates should only be done by authorised users and should be auditable e.g., create a separate `csc.admin.audit_log` table.

## Requirements
1. The CSC OMOP service should have a way of updating statuses e.g., approved, rejected, or backlog, of submitted project requests e.g., stored in the `csc.admin.projects` table.
2. The CSC OMOP service should be able to restrict these updates to certain users only.
3. The CSC OMOP service should be able to report on when and by whom these updates were made.

## Acceptance Criteria
- [ ] The CSC OMOP service has a `ProjectManager` that enables the updating of project statuses e.g., in the `csc.admin.projects` table via e.g., dynamic `INSERT` scripts.
- [ ] The `ProjectManager` will accept this update action from authorised users only.
- [ ] The `ProjectManager` is able to track details of when and by whom these updates were made e.g., create a separate `csc.audit.project_log` table and trigger function to update the `project_log` table based on updates to the `csc.admin.projects` table.

## Testing Guidance
- Run `pytest tests/`

**Comment by heyhaleema** [comment]
Covered by #78.
