### ISSUE TITLE
SRS-001: CSC OMOP database will be hosted in a public GitHub repository.

### ISSUE THREAD

**Issue by dangerdika** [GSTT-CSC/OMOP#4]
## Description
The scripts used to set up, maintain, interaction with, etc. the CSC OMOP database and its related automated data pipeline should be hosted on a public GitHub repository to facilitate easy collaboration and code transparency. 

:warning: **No personally identifiable information (PII) e.g., patient numbers, imaging unique identifiers, etc., should be uploaded**. 

Business logic is generally acceptable but if in doubt, please double check with the project leads.

## Requirements
1. The scripts used to set up, maintain, interaction with, etc. the CSC OMOP database and its related automated data pipeline should be hosted on a public GitHub repository.

## Acceptance Criteria
- [ ] The GitHub repository in which the scripts used to set up, maintain, interaction with, etc. the CSC OMOP database and its related automated data pipeline is accessible by all users e.g., regardless of whether an individual has a GitHub user account, their GitHub user organisation, etc.

## Testing Guidance
- Navigate to the GitHub repository in Incognito mode on any web browser.

**Comment by heyhaleema** [comment]
Acceptance criteria is satisfied.

>## Acceptance Criteria
>- [x]  The GitHub repository in which the scripts used to set up, maintain, interaction with, etc. the CSC OMOP database and its related automated data pipeline is accessible by all users e.g., regardless of whether an individual has a GitHub user account, their GitHub user organisation, etc.
