### ISSUE TITLE
BUG-001 Circular dependency between `domain` and `concept` tables

### ISSUE THREAD

**Issue by AgatheZ** [GSTT-CSC/OMOP#40]
## Description
During data ingestion, a circular dependency between the `domain` and `concept` tables was encountered (see issue #38 for more information). This complicates the data ingestion process and currently requires temporarily disabling the foreign key constraints when ingesting both tables.

## Steps to Reproduce
1. Download SNOMED vocabulary files from OHDSI's [Athena](https://athena.ohdsi.org/search-terms/start)*
2. Ensure the `create_constraints.sql` and `create_indices.sql` scripts are in `init-scripts/`
3. Start the Docker container by running `docker compose --env-file ./config/dev/development.env up -d`
4. Navigate to http://localhost:5050/browser/
5. Connect to the `OMOP_dev` server
6. Go to Databases > Schema > omop_cdm > Tables
7. Right-click on the `concept` table and select "Import/Export Data"
8. Select the matching vocabulary file i.e., CONCEPT.CSV, and press "OK"

## Expected behaviour
Tables, along with constraints, to be created without issue.

## Screenshots
![Uploading 275985645-b76e4148-0a6c-47f6-b1e3-da20bbd21d07.png…]()

## Desktop 
 - OS: [e.g. iOS] Windows
 - VS Code

## Additional Information
A possible solution is to modify the constraints script e.g., see the example provided in [this GitHub issue](https://github.com/OHDSI/CommonDataModel/issues/543) in OHDSI's CommonDataModel GitHub repository of how constraints can be modified.

**Comment by heyhaleema** [comment]
Based on [this discussion](https://forums.ohdsi.org/t/newbie-vocabulary-import/574/41) in the OHDSI forum, we've taken the approach that data should be copied into the tables first i.e., before constraints are applied during the database's initial setup. As mentioned in above and @AgatheZ's PR #38, we may need to ad hoc disable/re-enable constraints going forward.
