### ISSUE TITLE
SRS-002: CSC OMOP service will allow user feedback to be submitted via GitHub issues.

### ISSUE THREAD

**Issue by dangerdika** [GSTT-CSC/OMOP#5]
## Description
The CSC OMOP service i.e., the OMOP PostgreSQL database itself, its automated data pipeline, the Python, SQL, etc., scripts that underpin the service, etc., should allow users to provide feedback, submit bug reports, request new features, etc., via [GitHub issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue).

⚠️ Requires users to be signed into GitHub.

## Requirements
1. The CSC OMOP service should have a core, public GitHub repository i.e., enables all GitHub users to raise issues.

## Acceptance Criteria
- [ ] The CSC OMOP service has a core, public GitHub repository i.e., enables all GitHub users to raise issues.

## Testing Guidance
1. Navigate to the CSC OMOP service has a core, public GitHub repository on any web browser.
2. Click on the **Issues** tab.
3. Click on the **New issue** button on the top right-hand side to create a new issue.

**Comment by heyhaleema** [comment]
Acceptance criteria is satisfied.

> ## Acceptance Criteria
> * [x]  The CSC OMOP service has a core, public GitHub repository i.e., enables all GitHub users to raise issues.
