### ISSUE TITLE
SRS-004: CSC OMOP service core GitHub repository will contain and track documentation of agreed actions.

### ISSUE THREAD

**Issue by dangerdika** [GSTT-CSC/OMOP#7]
## Description
The CSC OMOP service's i.e., the OMOP PostgreSQL database itself, its automated data pipeline, the Python, SQL, etc., scripts that underpin the service, etc., core GitHub repository should contain and track documentation of agreed actions with stakeholders e.g., via user requirements documents, GitHub issues, etc.

## Requirements
1. The CSC OMOP service should have a core, public GitHub repository in which agreed actions can be stored.

## Acceptance Criteria
- [ ] The CSC OMOP service has a core, public GitHub repository in which agreed actions can be stored i.e., latest versions tracked in the `main` branch.

## Testing Guidance
- Navigate to the CSC OMOP service has a core, public GitHub repository on any web browser.
- View documentation in `main` branch.

**Comment by heyhaleema** [comment]
Acceptance criteria is satisfied.

> ## Acceptance Criteria
> * [x]  The CSC OMOP service has a core, public GitHub repository in which agreed actions can be stored i.e., latest versions tracked in the `main` branch e.g., in the [`documentation` directory](https://github.com/GSTT-CSC/OMOP/tree/main/documentation).
